server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: manhattan

logging:
  level:
    root: INFO
    com.manhattan: INFO
    org.springframework.web.socket: WARN
    org.springframework.messaging: WARN
