server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://username:9J4PUui2X4MQMeAi@manhattan.2wyxkav.mongodb.net/?appName=manhattan
      database: manhattan

logging:
  level:
    root: INFO
    com.manhattan: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.data.mongodb: DEBUG
